[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/villes"
  to = "/villes/cambrai.html"
  status = 301

# Security headers / SW
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]
[[redirects]]
from = "/rachat"
to = "/reprise.html"
status = 301

[[redirects]]
from = "/rachat.html"
to = "/reprise.html"
status = 301
